### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [hyotang666/null-package#3]
Building with SBCL 2.2.4 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id d62777aed0f9f166b2e3e3a9f233d118e074aadd

*null-package.test* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: The variable ECLECTOR.READER::*LABELS* is unbound.(in form starting at line: 271, column: 0, position: 6424)
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "null-package.test" "null-package">

```

[Full log here](http://report.quicklisp.org/2022-06-21/failure-report/null-package.html)

**Comment by hyotang666** [comment]
Thank you for reporting.
This is related to jingoh.reader and the bug is fixed in jingoh.reader side.
